---

ospf_routers:
  
  - hostname: R1
    routing_protocol: ospf
    mgmt_ip: 10.0.0.1
    router_ID: 1.1.1.1
    profile: router
    routed_networks:
      
      - network: 192.168.1.0
        wildcard_mask: 0.0.0.255

      - network: 192.168.2.0
        wildcard_mask: 0.0.0.255

      - network: 192.168.3.0
        wildcard_mask: 0.0.0.255
  
  - hostname: R2
    routing_protocol: ospf
    mgmt_ip: 10.0.0.2
    router_id: 2.2.2.2
    profile: router
    routed_networks:

      - network: 192.168.1.0
        wildcard_mask: 0.0.0.255

      - network: 192.168.2.0
        wildcard_mask: 0.0.0.255

      - network: 192.168.3.0
        wildcard_mask: 0.0.0.255