---
- name: Testing getting interfaces from napalm
  hosts: switch
  gather_facts: no
  connection: local

  tasks:
    
    - name: Getting interface details from target device
      napalm_get_facts:
        provider: "{{ creds }}"
        filter: "interfaces,interfaces_ip"
    - debug: var=napalm_interfaces
    - debug: var=napalm_interfaces_ip
